parameters:
  terraformVersion: '1.5.7'  # Not used anymore unless you re-enable installer

stages:
  - stage: Init
    displayName: 'Terraform Init'
    jobs:
      - job: Init
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean Terraform Cache'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - script: |
              echo "Using system-installed Terraform:"
              which terraform
              terraform -version
            displayName: 'Verify Terraform Binary'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              # useTerraformVersion is intentionally omitted for system binary
