parameters:
  terraformVersion: '1.5.7'

stages:
  - stage: Validate
    displayName: 'Terraform Validate'
    dependsOn: Init
    jobs:
      - job: Validate
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean .terraform and lockfile'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: ${{ parameters.terraformVersion }}

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init (Validate)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              useTerraformVersion: ${{ parameters.terraformVersion }}

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              useTerraformVersion: ${{ parameters.terraformVersion }}
